spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gedservice?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    driver-code-class: com.mysql.jdbc.Driver
  security:
    user:
      password: d8d93801-c78a-4dc1-9a4e-726b01239e3f

  jpa:
    generate-ddl: true
    database: MYSQL
    show-sql: false

  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  logging:
    level:
      root: DEBUG

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8081